#!/bin/sh

# Horizontal monitor
H=DP-4
# Vertical monitor
V=DP-0

bspc monitor $H --reset-desktops 一 二 三 四 五 六 七 八 九 十
bspc monitor $V --reset-desktops 一 二 三 四 五 六 七 八 九 十 辞 暗 ア

bspc config border_width 5
bspc config window_gap 0
bspc config -m $H top_padding 35
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config pointer_follows_monitor true
bspc config external_rules_command ~/.config/bspwm/external_rules

bspc config normal_border_color "$(xrdb -get color0)"
bspc config active_border_color "$(xrdb -get color7)"
bspc config focused_border_color "$(xrdb -get color15)"
bspc config presel_feedback_color "$(xrdb -get color7)"

bspc rule --add 'scratchpad:st:*' monitor=$H state=floating hidden=on sticky=on locked=on rectangle=3000x1800+420+180
bspc rule --add 'Genymotion Player:*:*' desktop=$V:^13 locked=on
# bspc rule --add 'Anki:anki:main - Anki' desktop=$V:^12
# bspc rule --add 'Anki:anki:Migaku Dictionary' desktop=$V:^11 state=fullscreen locked=on
bspc rule --add 'pick-song:st:*' state=floating
bspc rule --add 'MEGAsync:megasync:*' state=floating rectangle=100x100+3020+0
bspc rule --add 'Hydrus Client:client.pyw:*' desktop=$H^10 layer=above
bspc rule --add 'Hydrus Client:client.pyw:hydrus client media viewer' monitor=$V state=fullscreen layer=normal

pgrep -fx -- 'st -c scratchpad' || st -c scratchpad
