#!/bin/sh

bspc monitor 'DP-4' --reset-desktops 一 二 三 四 五 六 七 八 九 十
bspc monitor 'DP-0' --reset-desktops 一 二 三 四 五 六 七 八 九 十 辞 暗 ア

bspc config border_width 5
bspc config window_gap 0
bspc config -m DP-4 top_padding 35
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false
bspc config external_rules_command ~/.config/bspwm/external_rules

bspc config normal_border_color "$(xrdb -get color7)"
bspc config active_border_color "$(xrdb -get color15)"
bspc config focused_border_color "$(xrdb -get color4)"
bspc config presel_feedback_color "$(xrdb -get color7)"

bspc rule --add 'scratchpad:st:*' monitor=DP-4 state=floating hidden=on sticky=on locked=on rectangle=3000x1800+420+180
# bspc rule --add 'Genymotion Player:*:*' desktop=DP-0:^13 state=fullscreen locked=on
bspc rule --add 'Anki:anki:main - Anki' desktop=DP-0:^12
bspc rule --add 'Anki:anki:Migaku Dictionary' desktop=DP-0:^11 state=fullscreen locked=on
bspc rule --add 'pick-song:st:*' state=floating
bspc rule --add 'MEGAsync:megasync:*' state=floating rectangle=100x100+3020+0
bspc rule --add 'Hydrus Client:client.pyw:*' desktop=DP-1^10 layer=above
bspc rule --add 'Hydrus Client:client.pyw:hydrus client media viewer' state=fullscreen layer=normal
# bspc rule --add 'Hydrus Client:client.pyw:hydrus client' layer=normal

pgrep -fx -- 'st -c scratchpad' || st -c scratchpad
