require "ott.options"
require "ott.keymaps"
require "ott.plugins"

require "ott.plugin_configs.auto-pairs"
require "ott.plugin_configs.vimwiki"
require "ott.plugin_configs.vimtex"
require "ott.plugin_configs.luasnip"
require "ott.plugin_configs.nvim-cmp"
require "ott.plugin_configs.lsp"
require "ott.plugin_configs.null-ls"
